name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as secret

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dockerfile:23f1000864 .

      # Step 4: Push the image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerfile:23f1000864
